the scrum number is 60
younespro1337/Work-Hub pull request #4
Opened 2024-10-18 12:48 UTC by Muktadirnayem66

working task the scrum number is 50

2024-10-18 13:16 UTC, younespro1337 requested changes
Thank you for your work on this feature. There are a few changes that need to be addressed before merging:

Update the Terms-condition component so that it only contains the return() statement.
Move the Snackbar logic to the Hero page.
Make sure the subscription call is made from the Hero page to send emails to the backend, and handle the 404 status response as expected.
Please address these changes, and let me know once they’re done so we can proceed with the merge.

2024-10-18 13:16 UTC, younespro1337 commented on frontend/src/components/NewHome/components/TermsConditions.js
> +  const [snackbarMessage, setSnackbarMessage] = useState("Hello, I'm the Terms & Conditions page.");
Move the Snackbar component to the Hero page. The Terms-Condition component should only contain the return() statement

2024-10-18 13:16 UTC, younespro1337 commented on frontend/src/components/NewHome/components/Hero.js
> +            <Link href="/terms-conditions" color="primary">
Link Is Approval

2024-10-18 13:16 UTC, younespro1337 commented on frontend/src/App.js
> +                  <Route path='/terms-conditions' element={<TermsConditions/>}/>
Approval granted—just make sure the terms-conditions route is not protected.

2024-10-18 13:16 UTC, younespro1337 commented on frontend/src/components/NewHome/components/Hero.js
> -            <Link href="#" color="primary">
Make sure to call the subscription function from the Hero page to send the email to the backend. Use the Snackbar to display the message in the UI—no problem there. Also, expect a 404 status in case of any issues with the request.

2024-10-25 12:26 UTC, closed without merging

2024-10-25 12:28 UTC, Muktadirnayem66 commented
close the poll request.